server:
  port: 8888

spring:

  cloud:
    config:
      server:
        git:
          uri: git@github.com:emrygun/spring-cloud-config-server-demo.git
          clone-on-start: true
          search-paths:
            - config

  security:
    user:
      name: root
      password: s3cr3t

logging:
  level:
    root: debug
